"""
ThreatLens AI - Security Alert Endpoints
Manages threat alert triage, status transitions, and unread counts.
"""

from typing import List, Optional
from fastapi import APIRouter, Depends, HTTPException, Query, status

from app.api.deps import get_optional_current_user
from app.schemas.scan import AlertResponse, AlertUpdate
from app.services.db import get_alert_records, update_alert_record


router = APIRouter(prefix="/alerts", tags=["Security Alerts"])


@router.get("", response_model=List[AlertResponse])
async def list_alerts(
    status_filter: Optional[str] = Query(None, alias="status"),
    limit: int = Query(50, ge=1, le=100),
    current_user: Optional[dict] = Depends(get_optional_current_user),
):
    """
    Retrieves security alerts generated by high/critical threat scans.
    """
    user_id = current_user.get("id") if current_user else None
    alerts = get_alert_records(user_id=user_id, limit=limit)

    if status_filter:
        alerts = [a for a in alerts if a.get("status", "").upper() == status_filter.upper()]

    return alerts


@router.patch("/{alert_id}", response_model=AlertResponse)
async def update_alert(
    alert_id: str,
    payload: AlertUpdate,
    current_user: Optional[dict] = Depends(get_optional_current_user),
):
    """
    Updates status (OPEN, INVESTIGATING, RESOLVED, DISMISSED) or read state of an alert.
    """
    updates = {}
    if payload.status is not None:
        valid_statuses = ["OPEN", "INVESTIGATING", "RESOLVED", "DISMISSED"]
        if payload.status.upper() not in valid_statuses:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=f"Invalid status. Must be one of: {', '.join(valid_statuses)}",
            )
        updates["status"] = payload.status.upper()

    if payload.is_read is not None:
        updates["is_read"] = payload.is_read

    updated = update_alert_record(alert_id, updates)
    if not updated:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Alert with ID {alert_id} not found.",
        )
    return updated


@router.post("/{alert_id}/resolve", response_model=AlertResponse)
async def resolve_alert(
    alert_id: str,
    current_user: Optional[dict] = Depends(get_optional_current_user),
):
    """
    Convenience endpoint to immediately mark an alert as RESOLVED and read.
    """
    updated = update_alert_record(alert_id, {"status": "RESOLVED", "is_read": True})
    if not updated:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Alert with ID {alert_id} not found.",
        )
    return updated
