import React, { useState, useEffect } from 'react';
import {
  FileText,
  Plus,
  Printer,
  Download,
  Eye,
  X,
  ShieldAlert,
  RotateCw
} from 'lucide-react';
import { Button } from '../components/ui/Button';
import { Input } from '../components/ui/Input';
import { Dropdown } from '../components/ui/Dropdown';
import { Table } from '../components/ui/Table';
import type { Column } from '../components/ui/Table';
import { Modal } from '../components/ui/Modal';
import { LoadingState } from '../components/ui/LoadingState';
import { ThreatLensApi } from '../services/api';
import type { SecurityReportItem } from '../data/mockAnalyticsData';
import { formatRelativeTime } from '../utils/formatters';

export const ReportsPage: React.FC = () => {
  const [reports, setReports] = useState<SecurityReportItem[]>([]);
  const [selectedReport, setSelectedReport] = useState<SecurityReportItem | null>(null);
  const [isLoading, setIsLoading] = useState<boolean>(true);

  // Generate Report Modal State
  const [isGenerateModalOpen, setIsGenerateModalOpen] = useState<boolean>(false);
  const [newTitle, setNewTitle] = useState<string>('Quarterly Incident & Threat Classification Report');
  const [newType, setNewType] = useState<SecurityReportItem['type']>('Malware Classification Report');
  const [newPeriod, setNewPeriod] = useState<string>('August 2026');

  const loadReports = async () => {
    setIsLoading(true);
    const data = await ThreatLensApi.getSecurityReports();
    setReports(data);
    setIsLoading(false);
  };

  useEffect(() => {
    loadReports();
  }, []);

  const handleGenerateReport = async () => {
    setIsLoading(true);
    const created = await ThreatLensApi.createSecurityReport(newTitle, newType, newPeriod);
    setReports((prev) => [created, ...prev]);
    setIsGenerateModalOpen(false);
    setSelectedReport(created);
    setIsLoading(false);
  };

  const reportColumns: Column<SecurityReportItem>[] = [
    {
      key: 'title',
      header: 'Report Document Title',
      render: (item) => (
        <div className="flex flex-col min-w-0">
          <span className="font-mono text-xs font-bold text-slate-100 truncate flex items-center gap-1.5">
            <FileText className="w-3.5 h-3.5 text-sky-400 shrink-0" />
            <span>{item.title}</span>
          </span>
          <span className="text-2xs text-slate-500 font-mono mt-0.5">
            {item.id} • {item.type}
          </span>
        </div>
      ),
    },
    {
      key: 'period',
      header: 'Reporting Period',
      render: (item) => <span className="font-mono text-2xs text-slate-300 font-semibold">{item.period}</span>,
    },
    {
      key: 'generatedBy',
      header: 'Generated By',
      render: (item) => <span className="font-mono text-2xs text-sky-300">{item.generatedBy}</span>,
    },
    {
      key: 'generatedDate',
      header: 'Generated Date',
      render: (item) => (
        <span className="font-mono text-2xs text-slate-400">
          {formatRelativeTime(item.generatedDate)}
        </span>
      ),
    },
    {
      key: 'status',
      header: 'Status',
      align: 'center',
      render: (item) => (
        <span className="font-mono text-2xs font-bold px-2 py-0.5 rounded border bg-emerald-950/70 text-emerald-400 border-emerald-800/80">
          {item.status}
        </span>
      ),
    },
    {
      key: 'actions',
      header: 'Actions',
      align: 'right',
      render: (item) => (
        <div className="flex items-center justify-end gap-1.5">
          <Button
            variant="primary"
            size="xs"
            leftIcon={<Eye className="w-3 h-3" />}
            onClick={() => setSelectedReport(item)}
          >
            Preview
          </Button>
          <Button
            variant="subtle"
            size="xs"
            leftIcon={<Download className="w-3 h-3" />}
            onClick={() => alert(`Exporting STIX 2.1 JSON bundle for ${item.id}...`)}
          >
            STIX 2.1
          </Button>
        </div>
      ),
    },
  ];

  return (
    <div className="space-y-5 select-none font-sans">
      {/* Header Banner */}
      <div className="p-3.5 bg-slate-900 border border-slate-800 rounded flex flex-col md:flex-row md:items-center justify-between gap-3">
        <div>
          <h1 className="text-sm font-bold tracking-wider font-mono text-slate-100 uppercase flex items-center gap-2">
            <FileText className="w-4 h-4 text-sky-400" />
            <span>Forensic Incident & Threat Intelligence Reports</span>
          </h1>
          <p className="text-2xs text-slate-400 font-mono mt-0.5">
            STIX 2.1 Compliant Summaries • Executive Forensic Documents • API Export Ready
          </p>
        </div>

        <div className="flex items-center gap-2">
          <Button
            variant="secondary"
            size="xs"
            leftIcon={<RotateCw className="w-3 h-3" />}
            onClick={loadReports}
          >
            Refresh Catalog
          </Button>
          <Button
            variant="primary"
            size="xs"
            leftIcon={<Plus className="w-3 h-3" />}
            onClick={() => setIsGenerateModalOpen(true)}
          >
            Generate Security Report
          </Button>
        </div>
      </div>

      {/* Reports Table */}
      {isLoading ? (
        <LoadingState message="Loading Forensic Security Reports Catalog..." />
      ) : (
        <Table
          columns={reportColumns}
          data={reports}
          keyExtractor={(item) => item.id}
          onRowClick={(item) => setSelectedReport(item)}
        />
      )}

      {/* Generate Report Modal */}
      <Modal
        isOpen={isGenerateModalOpen}
        onClose={() => setIsGenerateModalOpen(false)}
        title="Generate Formal Security Report"
      >
        <div className="space-y-4 font-mono text-2xs">
          <Input
            label="Report Title"
            value={newTitle}
            onChange={(e) => setNewTitle(e.target.value)}
            isMonospace
          />

          <Dropdown
            label="Report Specification Type"
            value={newType}
            onChange={(val) => setNewType(val as SecurityReportItem['type'])}
            options={[
              { value: 'Malware Classification Report', label: 'Malware Classification Report' },
              { value: 'Threat Monitoring Report', label: 'Threat Monitoring Report' },
              { value: 'Security Analytics Report', label: 'Security Analytics Report' },
              { value: 'Investigation Report', label: 'Investigation Report' },
            ]}
          />

          <Input
            label="Reporting Period Window"
            value={newPeriod}
            onChange={(e) => setNewPeriod(e.target.value)}
            isMonospace
          />

          <div className="pt-2 flex justify-end gap-2">
            <Button variant="ghost" size="xs" onClick={() => setIsGenerateModalOpen(false)}>
              Cancel
            </Button>
            <Button variant="primary" size="xs" onClick={handleGenerateReport}>
              Generate Report
            </Button>
          </div>
        </div>
      </Modal>

      {/* PROFESSIONAL EXECUTIVE REPORT PREVIEW MODAL */}
      {selectedReport && (
        <div className="fixed inset-0 bg-slate-950/80 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-slate-900 border border-slate-750 rounded-lg shadow-2xl max-w-3xl w-full max-h-[90vh] overflow-y-auto font-mono text-2xs select-text">
            {/* Report Header Bar */}
            <div className="p-4 bg-slate-950 border-b border-slate-800 flex items-center justify-between sticky top-0 z-10">
              <div className="flex items-center gap-2">
                <ShieldAlert className="w-4 h-4 text-sky-400" />
                <span className="font-bold text-xs text-slate-100 uppercase tracking-widest">
                  ThreatLens AI — Confidential Forensic Security Report
                </span>
              </div>
              <div className="flex items-center gap-2">
                <Button
                  variant="secondary"
                  size="xs"
                  leftIcon={<Printer className="w-3 h-3" />}
                  onClick={() => window.print()}
                >
                  Print Report
                </Button>
                <Button
                  variant="primary"
                  size="xs"
                  leftIcon={<Download className="w-3 h-3" />}
                  onClick={() => alert(`STIX 2.1 JSON bundle exported for ${selectedReport.id}`)}
                >
                  Export STIX 2.1
                </Button>
                <button
                  type="button"
                  onClick={() => setSelectedReport(null)}
                  className="text-slate-400 hover:text-slate-100 p-1 rounded hover:bg-slate-800"
                >
                  <X className="w-4 h-4" />
                </button>
              </div>
            </div>

            {/* Document Body */}
            <div className="p-6 space-y-5 text-slate-200">
              {/* Document Header Metadata */}
              <div className="p-4 bg-slate-950 border border-slate-800 rounded space-y-2">
                <div className="flex justify-between items-start border-b border-slate-850 pb-2">
                  <div>
                    <h1 className="text-sm font-bold text-slate-100">{selectedReport.title}</h1>
                    <span className="text-sky-400 font-semibold">{selectedReport.type}</span>
                  </div>
                  <span className="px-2 py-0.5 rounded bg-sky-950 text-sky-400 border border-sky-800 font-bold">
                    {selectedReport.id}
                  </span>
                </div>

                <div className="grid grid-cols-2 sm:grid-cols-3 gap-2 text-2xs pt-1">
                  <div>
                    <span className="text-slate-500 block">Generated Date:</span>
                    <span className="text-slate-200 font-semibold">{selectedReport.generatedDate}</span>
                  </div>
                  <div>
                    <span className="text-slate-500 block">Generated By:</span>
                    <span className="text-slate-200 font-semibold">{selectedReport.generatedBy}</span>
                  </div>
                  <div>
                    <span className="text-slate-500 block">Time Period:</span>
                    <span className="text-slate-200 font-semibold">{selectedReport.period}</span>
                  </div>
                </div>
              </div>

              {/* Executive Summary */}
              <div className="space-y-1.5">
                <h2 className="text-xs font-bold uppercase tracking-wider text-sky-400 border-b border-slate-800 pb-1">
                  1. Executive Summary
                </h2>
                <p className="text-slate-300 leading-relaxed bg-slate-950 p-3 rounded border border-slate-850">
                  {selectedReport.summary}
                </p>
              </div>

              {/* Key Forensic Findings */}
              <div className="space-y-1.5">
                <h2 className="text-xs font-bold uppercase tracking-wider text-amber-400 border-b border-slate-800 pb-1">
                  2. Key Forensic & Classification Findings
                </h2>
                <div className="space-y-1 bg-slate-950 p-3 rounded border border-slate-850">
                  {selectedReport.keyFindings.map((finding, idx) => (
                    <div key={idx} className="flex items-start gap-2 text-slate-200">
                      <span className="text-amber-400 font-bold">•</span>
                      <span>{finding}</span>
                    </div>
                  ))}
                </div>
              </div>

              {/* Extracted Indicators of Compromise */}
              <div className="space-y-1.5">
                <h2 className="text-xs font-bold uppercase tracking-wider text-sky-400 border-b border-slate-800 pb-1">
                  3. Extracted Threat Indicators (IOC List)
                </h2>
                <div className="space-y-1 bg-slate-950 p-3 rounded border border-slate-850">
                  {selectedReport.iocs.map((ioc, idx) => (
                    <div key={idx} className="text-emerald-300">
                      <code>{ioc}</code>
                    </div>
                  ))}
                </div>
              </div>

              {/* Recommended Incident Response Actions */}
              <div className="space-y-1.5">
                <h2 className="text-xs font-bold uppercase tracking-wider text-red-400 border-b border-slate-800 pb-1">
                  4. Recommended Incident Response & Containment Plan
                </h2>
                <div className="space-y-1 bg-red-950/20 p-3 rounded border border-red-900/60 text-slate-200">
                  {selectedReport.recommendedActions.map((act, idx) => (
                    <div key={idx} className="flex items-start gap-2">
                      <span className="text-red-400 font-bold">▶</span>
                      <span>{act}</span>
                    </div>
                  ))}
                </div>
              </div>

              {/* Report Footer Verification */}
              <div className="pt-4 border-t border-slate-800 flex justify-between items-center text-slate-500 text-2xs">
                <span>ThreatLens AI Intelligence Engine v4.2 • Verification Signature OK</span>
                <span>Page 1 of 1</span>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
